### ISSUE TITLE
 BrainCloud Unity SDK no longer works in Unity 2020.1B16   

### ISSUE THREAD

**Issue by kenofori** [getbraincloud/braincloud-csharp#145]
Hi there,

I switched to Unity 2020.1B16 and BrainCloud SDK on Android Platform doesnt seem to work any more and throw a editor time error. I raised this issue on support but havent heard anything so posting here too.

Question is why a WebGL Platformerror is not letting me use it for Android especially when we can use conditional compilation.

Please advise

Deterministic compilation failed. You can disable Deterministic builds in Player Settings
Assets\BrainCloud\UnityWebSocketsForWebGL\WebSocketSharp\AssemblyInfo.cs(20,28): error CS8357: The specified version string contains wildcards, which are not compatible with determinism. Either remove wildcards from the version string, or disable determinism for this compilation

**Comment by pascalf1309** [comment]
Hello kenofori,

thank you for reporting the issue, unfortunately brainCloud does not yet support Unity 2020 - but will do so in the future. We generally recommend that customers stick to stable Unity releases when possible.

**Comment by kenofori** [comment]
@pascalf1309 I understand reasoning behind sticking to 2019.

However 2020.1 launch is around the corner, and even if its not what i dont understand is why a WebGL Platform library interfaring with Android Plaform, If you use #if UNITY_WEBGL directive then all of that needless code disappear saving both compilation time as well as this problem im getting.

I cant switch to older version as i have been using this 2020.1 since day one for this game :(
So please do consider it

**Comment by ruth0048** [comment]
Hi there kenofori!

I did some digging for you, it looks like with Unity 2020 they are introducing a feature for deterministic building. 

You'll notice a flag that has been added if you go to File->Build Settings->Player Settings then under the Player tab go into Other Settings and scroll down to Configuration until you see 
"Use deterministic compilation". This flag is not in 2019 version of Unity, and it defaults to being used in Unity 2020. That is why this new error is popping up. As the error recommends, 
you need to un-check that flag to stop deterministic builds and that will allow you to build and run your project once again. 

As to your question, why this is all happening...
We can't speak on Unity's behalf as to why they're adding this feature, but we do see that the third party WebSocket library we use for certain platforms like WebGL is conflicting with this deterministic building.
The reason it conflicts is that it uses the "*" syntax which is variable and thus is incompatible with determinism. This is why you see the error with [assembly: AssemblyVersion("1.0.2.*")] where it uses "*"
in attempts to do automatic updates based on the revision of the AssemblyVersion. 

We appreciate you bringing up this issue with us as we will need to address this in some manner. 

For now a temporary solution for you is to turn this flag off. If you weren't planning on having deterministic builds in your project then that is the simplest solution. An alternative would be to edit
this line [assembly: AssemblyVersion("1.0.2.*")] manually in the AssemblyInfo.cs file and decide on a specific revision for the WebSocket library to associate with like [assembly: AssemblyVersion("1.0.2")]. 

Hope this works for you!

Ryan Ruth

**Comment by ruth0048** [comment]
This has been fixed as of release 4.5.6
